export const GET_CHAT_START = 'GET_CHAT_START'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'

export const GET_CHATS_START = 'GET_CHATS_START'
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS'
